<a href="https://colab.research.google.com/github/srijita1406/Cross-validation-in-ML/blob/main/Mock1_OPPE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [131]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [132]:
from sklearn.datasets import load_breast_cancer

In [133]:
df1=load_breast_cancer()

In [134]:
df= pd.DataFrame(data=df1.data,columns=df1.feature_names)


In [135]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [137]:
df.shape

(569, 30)

In [138]:
feature_list=df.columns[:-1].values
print(feature_list)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry']


In [139]:
feature_list.size

29

In [140]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
dtype: int64

In [141]:
target=[]
target=df1.target
print(target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [142]:
cancer=df1.target_names
print(cancer)

['malignant' 'benign']


In [143]:
y=target.reshape(1,-1)
print(y)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1
  0 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1
  0 1 1 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1
  1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1
  0 0 0 1 0 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0
  1 1 0 0 1 1 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1
  1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0
  1 1 1 1 0 0 0 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1
  1 1 1 1 1 0 0 1 0 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1
  1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1
  0 0 1 0 1 1 1 1 1 0 1 1 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1
  0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 

In [144]:
(y==0).sum()

212

In [145]:
df['mean perimeter'].corr(df['mean radius'])

0.9978552814938106

In [146]:
data=[[7, 16, 31], [np.nan, np.nan, 66], [12, 5, np.nan],[98, np.nan, 92]]

In [147]:
from sklearn.impute import SimpleImputer
Imputer=SimpleImputer(strategy='mean')
Imputer.fit_transform(data)


array([[ 7. , 16. , 31. ],
       [39. , 10.5, 66. ],
       [12. ,  5. , 63. ],
       [98. , 10.5, 92. ]])

In [148]:
from sklearn.preprocessing import FunctionTransformer

In [149]:
transformer=FunctionTransformer(np.log10)
X=[[1, 1], [2, 3],[10,100]]

In [150]:
transformer.transform(X)

array([[0.        , 0.        ],
       [0.30103   , 0.47712125],
       [1.        , 2.        ]])

In [151]:
df2=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data' )
df2.columns=['sepal length', 'sepal width', 'petal length', 'petal width','label']
df3=df2.copy()


In [152]:
df3.head()

sepal length  sepal width  petal length  petal width        label
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

In [153]:
df4=df3.drop(columns='label')

In [154]:
from sklearn.preprocessing import PolynomialFeatures

In [155]:
polynom=PolynomialFeatures(degree=2)

In [156]:
df5=polynom.fit_transform(df4)

In [157]:
df2.shape

(149, 5)

In [158]:
df5.shape

(149, 15)

In [159]:
polynom.get_feature_names_out()

array(['1', 'sepal length', 'sepal width', 'petal length', 'petal width',
       'sepal length^2', 'sepal length sepal width',
       'sepal length petal length', 'sepal length petal width',
       'sepal width^2', 'sepal width petal length',
       'sepal width petal width', 'petal length^2',
       'petal length petal width', 'petal width^2'], dtype=object)

In [160]:
from sklearn.datasets import fetch_california_housing
housing=fetch_california_housing(return_X_y=True)

In [161]:
from sklearn.feature_selection import SelectPercentile, mutual_info_regression
X,y=housing

In [162]:
sk=SelectPercentile(mutual_info_regression,percentile=10)

In [163]:
hf=sk.fit_transform(X,y)

In [164]:
hf.shape

(20640, 1)

In [260]:
import numpy as np
from sklearn.datasets import fetch_california_housing

In [261]:
X,y=fetch_california_housing(return_X_y=True)

In [262]:
from sklearn.model_selection import train_test_split

In [309]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [310]:
X_train.shape

(16512, 8)

In [311]:
from sklearn.dummy import DummyRegressor

In [312]:

dummy=DummyRegressor(strategy='mean')

In [313]:
dummy.fit(X_train,y_train)

DummyRegressor()

In [314]:
dummy.predict(X_test)

array([2.07735064, 2.07735064, 2.07735064, ..., 2.07735064, 2.07735064,
       2.07735064])

In [315]:
dummy.score(X_test,y_test)

-0.0014734336890012134

In [270]:
from sklearn.linear_model import LinearRegression

In [272]:
lr=LinearRegression()

In [274]:
lr.fit(X_train,y_train)

LinearRegression()

In [275]:
lr.predict(X_test)

array([2.4007465 , 1.9352427 , 0.22869795, ..., 2.35345965, 2.06943524,
       1.26126934])

In [276]:
lr.score(X_test,y_test)

0.6010147914553838

In [279]:
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler

In [281]:
sgd=Pipeline([('min_max',MinMaxScaler()),('sgd_regressor',SGDRegressor())])


In [282]:
sgd.fit(X_train,y_train)

Pipeline(steps=[('min_max', MinMaxScaler()), ('sgd_regressor', SGDRegressor())])

In [291]:
y_predict=sgd.predict(X_train)

In [285]:
from sklearn.metrics import mean_absolute_error

In [292]:
eval_score=mean_absolute_error(y_train,y_predict)

In [293]:
print(eval_score)

0.5642029567684845


In [295]:
y_predict=sgd.predict(X_test)

In [297]:
eval_score1=mean_absolute_error(y_test,y_predict)

In [298]:
print(eval_score1)

0.5717097326284393


In [320]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression

In [323]:
score=cross_val_score(lr,X,y,cv=5)

In [324]:
print(score)

[0.54866323 0.46820691 0.55078434 0.53698703 0.66051406]


In [325]:
from sklearn.datasets import load_diabetes

In [327]:
df=load_diabetes(as_frame=True)

In [347]:
X7,y7=load_diabetes(return_X_y=True)

In [329]:
df1=df.frame

In [328]:
df.frame.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019908 -0.017646   151.0  
1 -0.039493 -0.068330 -0.092204    75.0  
2 -0.002592  0.002864 -0.025930   141.0  
3  0.034309  0.022692 -0.009362   206.0  
4 -0.002592 -0.031991 -0.046641   135.0

In [330]:
df1.shape

(442, 11)

In [338]:
from sklearn.preprocessing import StandardScaler

In [339]:
sd=StandardScaler()

In [342]:
df_23=sd.fit_transform(df1)

In [344]:
from sklearn.model_selection import train_test_split

In [362]:
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline

In [359]:
X_train,X_test,y_train,y_test=train_test_split(X7,y7,test_size=0.2,random_state=10)

In [365]:
estimators=('sd',StandardScaler()),('lg',LinearRegression())
pipe=Pipeline(steps=estimators)

In [366]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('sd', StandardScaler()), ('lg', LinearRegression())])

In [367]:
pipe.predict(X_test)

array([148.0978202 , 208.21400551, 186.40125844,  82.48876916,
       163.39689627, 126.17904513, 126.17880476, 264.70212482,
        78.54654307,  73.56261024, 124.46582144, 142.22854705,
       166.4549438 ,  98.5009742 ,  49.71902346, 223.51963411,
       143.44310503, 110.50382605, 202.53415354,  78.49893296,
       191.80901882, 243.20695862,  75.88822445, 214.90606332,
        55.73078912, 158.0288059 , 157.54022573, 158.88728076,
       166.2184483 , 107.63124236, 276.82392637, 179.20197197,
        60.48832138, 157.42965435, 218.98333103, 182.29672873,
        70.84400009, 186.74011272, 285.13886084, 196.19611072,
       202.26256246, 145.38319546, 215.02583484, 124.55391269,
        80.17027241,  98.99544054,  82.02453761,  83.40439369,
       289.99388729, 134.33663141, 112.1313993 , 152.32625919,
       109.90441466, 226.28134724, 245.74116064,  85.56172621,
       122.28262271, 139.20254207, 198.95361934, 120.92252444,
       179.99231965, 106.43580454, 123.03066928,  96.46

In [368]:
pipe.score(X_test,y_test)

0.5341962544929233

In [371]:
lg_coef=pipe[1]

In [372]:
lg_coef.coef_

array([ -0.18524015, -10.74395358,  23.97068421,  15.44649018,
       -33.63629412,  19.07747445,   3.87751116,  10.51831194,
        34.15440847,   1.91362494])

In [374]:
from sklearn.linear_model import RidgeCV

In [386]:
from sklearn.model_selection import cross_validate

In [377]:
alpha_list=np.logspace(-4,0,num=20)

In [384]:

ridge_reg_pipeline = Pipeline([("ridge_cv", RidgeCV(alphas=alpha_list,
store_cv_values=True))])

In [387]:
ridge_reg_cv_results = cross_validate(ridge_reg_pipeline,
X_train,
y_train,
cv=5,
scoring="neg_mean_absolute_error",
return_train_score=True,
return_estimator=True)

In [388]:
ridge_reg_train_error = -1 * ridge_reg_cv_results['train_score']

In [389]:
ridge_reg_train_error.mean()

43.69169270867296

In [394]:
from sklearn.metrics import mean_squared_error

In [395]:
sgd_reg = SGDRegressor(max_iter=1, tol=-np.infty, warm_start=True,
penalty=None, learning_rate="constant", eta0=0.0005)
for epoch in range(1000):
  sgd_reg.fit(X_train, y_train) # continues where it left off
  y_val_predict = sgd_reg.predict(X_test)
  val_error = mean_squared_error(y_test, y_val_predict)


In [398]:
from sklearn.model_selection import cross_validate
from sklearn.model_selection import ShuffleSplit
cv = ShuffleSplit(n_splits=40, test_size=0.3,
random_state=0)
cv_results = cross_validate(
lr, X, y,
cv=cv,
scoring=["neg_mean_absolute_error", "neg_mean_squared_error"],
return_train_score=True,
return_estimator=True)

In [401]:
print (cv_results)

{'fit_time': array([0.07923102, 0.0387454 , 0.0282793 , 0.03623581, 0.02036881,
       0.02123165, 0.02019596, 0.00843906, 0.00964522, 0.00690389,
       0.01488042, 0.00699806, 0.00707126, 0.01082325, 0.0093627 ,
       0.00683212, 0.00738192, 0.00695634, 0.00726843, 0.00866318,
       0.01192975, 0.00946856, 0.00672412, 0.02435803, 0.01415157,
       0.02031541, 0.00817943, 0.01177335, 0.00725651, 0.0068419 ,
       0.01761985, 0.01379275, 0.01922154, 0.01432109, 0.03151035,
       0.01989651, 0.00754285, 0.01423621, 0.01824021, 0.00682497]), 'score_time': array([0.00915885, 0.00126863, 0.0012641 , 0.00127172, 0.00123715,
       0.00134802, 0.00123549, 0.00121045, 0.00122166, 0.00114322,
       0.001261  , 0.00118518, 0.00551462, 0.00936341, 0.0012219 ,
       0.00116658, 0.0057683 , 0.00116873, 0.00115418, 0.00130463,
       0.00302386, 0.00122213, 0.00112605, 0.00687718, 0.00147486,
       0.00800705, 0.00123119, 0.00125146, 0.00113392, 0.0012331 ,
       0.00352454, 0.00126696, 0.